### ISSUE TITLE
Fix broken resource links

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#112]
a few of the (older?) resources have links that don't work. Need to fix

e.g. /resource/an-easy-introduction-to-biplots-for-multi-environment-trials
url:
"https://firebasestorage.googleapis.com/v0/b/stats4sd-resources.appspot.com/o/resources%2F-KjCjgkTDHzUs1f0BqMG%2FMcDermott%20and%20Coe%202012%20easy%20biplots.pdf?alt=media&token=2df4ce0a-6cdc-4148-932e-de9886be4ea3"

**Comment by chrismclarke** [comment]
I think it might just be the very first 4 or 5 resources, easily filtered from the all resources list

**Comment by dave-mills** [comment]
After brute-forcing the server with every url from the downloaded database, I've identified 6 files that need fixing. 

Probably easiest to fix from front-end by deleting file and re-uploading. Will do that when I can log in. 


[Files needed (json snippets - badly formatted).txt](https://github.com/stats4sd/SSD-Resources-Demo/files/1325021/Files.needed.json.snippets.-.badly.formatted.txt)

**Comment by chrismclarke** [comment]
Good to know, especially as it's just not the earliest uploads. Will definitely need to fix when pushed onto live. It would be good also if we could pass a list of resource IDs or better yet slugs to make it faster to identify (although I imagine you already have a pretty good guess). Also reminds me that any future search implementation would benefit from being able to search resource filenames too.

**Comment by chrismclarke** [comment]
I just went through the list, of the 6, three were actually working (mice, intro to stats games and intro analysis METs, I had a copy of the chirps guide, retrieved the missing stats game (woods) from the dropbox archive and found the other MET one online so should all be fine. @dave-mills, could you run same script on current live db to check and close if working?

**Comment by dave-mills** [comment]
Checked and all is good here :-)
