### ISSUE TITLE
Upgrade old tags 'type' field

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#116]
Current DB registers tags like 'Collections' however individual tag has type:'Collection'
Makes sense if it retains plural form for later use in identifier functions. Simple override of existing tags needed at some point, but not urgent.

**Comment by dave-mills** [comment]
Humm, yes. Starting to sort this out with keywords vs keyword (I think 'keyword' is still sitting in my persistedTags, and polluting things. Shouldn't be a major long-term problem). Going with the plural for the tag object as suggested, so its:

`"tags": {
 "Collections": {},
 "Keywords": {},
 "Resource-Types":{}
}`

**Comment by dave-mills** [comment]
Marking as done, as the format of "tags" with sub properties for Collections, Keywords and Resource-Types seems to be doing ok for now.
