### ISSUE TITLE
Prevent confusing/admin only features showing

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#119]
Many things are set to 'hidden' which has a delay before evaluating. This means that when some pages are loaded, parts load out of sequence and can look a bit odd; these sometimes include admin features. Suggest some sort of loading animation/start screen coupled with dom-if statements for anything admin (e.g. resource footer)

**Comment by dave-mills** [comment]
Closing this for now. I think the major culprits of this are all now using dom-if templates. Can add new issues for specific things that do this appear-disappear trick if we find any.
