### ISSUE TITLE
Merge common functions together for easy import

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#124]
There's a bit of replication going on, particularly with things like generateID() and some json/array manipulation. Could create a shared-functions instead.

**Comment by dave-mills** [comment]
Sounds like a very good idea for long-term maintenance / capacity building. I'm putting this into the "soon" category, but if there are quick things you can do to consolidate things in the next push, great :-)

**Comment by chrismclarke** [comment]
latest rewrite handles a lot of this, closing for now
