### ISSUE TITLE
firebase-auth error message on live

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#132]
It seems minifying messes up a bit (see thread:
https://github.com/Polymer/polymer-cli/issues/701)

Possible interim solution just to manually copy over firebase-auth into unbundled build folder before deploying. Needs testing

**Comment by chrismclarke** [comment]
copying files over seems to work, have added to readme and removing urgency on this (will still be better once proper solution found by polymer to reduce file size)

**Comment by dave-mills** [comment]
Have updated the Polymer build options to exclude all firebase scripts from minimisation. This seems to fix the issue without having to manually copy files each time (which I forgot to do last time, breaking the login on live...)

**Comment by dave-mills** [comment]
Closing for now, as I think this solution is vaguely stable.
