### ISSUE TITLE
Rich content descriptions for collections

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#143]
Add ability to include html description (wysiwyg editor?), and enhance some of the existing collections. (See more enhancement suggestions #144)

**Comment by chrismclarke** [comment]
We officially have Wysiwyg!!
Took quite a bit of wrangling and testing different elements and far from perfect but works reasonably well on collection descriptions. You can see in action on test esms course. Allows both for direct copy/paste html code as well as a visual editor. 

Known issues are the media import functions, most likely we'll want to add private methods to upload images/select from some sort of gallery and replace the button (easy to add custom buttons like has already been done with the save button). 

Next step is to test ( @dave-mills  could you?) and then document.

**Comment by dave-mills** [comment]
Tested and working (except for the media import as you already mentioned).
