### ISSUE TITLE
User direction features

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#144]
As discussed with Carlos, would be good to strategise more ways to help users find what they want. Should include:

tech - tag links on resources view, complete tagging processes, front page taglists, encourage local team to use, linked posts on related websites/user platforms/social media

**Comment by dave-mills** [comment]
I think this has 2 main components: 

1. Get keywords going (include in resource page; show on front page as 'cloud' (or something); include an admin keyword manager as a stretch-goal;

2. The social side - get key people to review the resources present, add more keywords, grow the collections etc...

**Comment by dave-mills** [comment]
This is a number of different issues, some of which have been partly handled (keywords are there but need linking, for e.g.) Splitting into different issues.
