### ISSUE TITLE
Search page seems non-responsive

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/Stats4SD-Resources-Site#157]
Search page doesn't give me any results. Not receiving any console errors, so it's possibly just not hooked up after the refactoring?

**Comment by chrismclarke** [comment]
Just to check, are you searching for a term that should return results? I like testing with the word ‘test’ as there’s quite a few like that.
I’ve already add to the dev branch a function to say ‘no results’ do you still have the issue?
https://ssd-resources-demo.firebaseapp.com/search

**Comment by dave-mills** [comment]
I was trying things that I thought should get results like search. I was looking on live. The dev's working fine (and can see the no-results' message. 

Oddly, the live is now working fine too (but without the no-results message, which makes sense!) I blame caching. 

Thanks!
