### ISSUE TITLE
Editing resource always takes me to the same resource

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/Stats4SD-Resources-Site#162]
Possibly related to issue #161...

When I click "edit resource" when looking at a resource, it always takes me to edit the first resource I went to edit this session. 

E.g: 

 - I go to the main resources list and click to view "CCAFS Data Management Strategy". 
 - I click "edit resource"
 - I click back to the main resources list, than choose a different resource.
 - I click "edit resource" to edit this different resource
 - I am taken to the editor, but I am now editing "CCAFS Data Management Strategy". 

Doesn't matter whether I make any edits, save draft or update the live resource or not. 

I say this might be related to #161, because of this: 

- After doing the above, I click "add resource". I am also taken to the editor and am editing CCAFS Data Management Strategy. 

My assumption is that the 'currently editing' resource is set once, then not overridden correctly.

**Comment by chrismclarke** [comment]
ah, the function to edit a url only gets called on creation of the resource page and strangely seems to be only on first creation (guessing doesn't get properly destroyed when navigating out of resource page mode to other pages). I've simply added the active resource parameter to the function call `__getEditResourceLink()` -> `_getEditResourceLink(resource)` which should trigger re-evaluation whenever the resource changes.

**Comment by chrismclarke** [comment]
actually that makes sense, as page rendering is handled by iron-pages which is just glorified hide/show (once a page has rendered once it never tries to restamp for better efficiency, and hence 'call-once' style functions need to be designed a little more carefully).
