### ISSUE TITLE
Decide on versioning convention

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Stats4SD-Resources-Site#71]
As mentioned in the meeting, 0.9,1.0 etc. lacks a certain pizazz. Open to suggestions.

**Comment by chrismclarke** [comment]
My current thinking is either something vaguely work-related like lists of grains/derivative foods, or maybe more simply the last thing eaten at time of creation.

**Comment by dave-mills** [comment]
I'm going with types of tea for major versions, as I was craving camomile tea when I thought about it.

For minor / point releases, it's still all to play for. First come first served.
